#!/bin/bash

# Mute indicator: a pre-rendered glowing LED strip image shown when muted.
# The image is generated by chezmoi (modify_ script in images/).
# Only event-driven updates — no polling (update_freq=0).

sketchybar --add event mic_change \
  \
  --add item mic.core center \
  --set mic.core \
        update_freq=0 \
        drawing=off \
        icon.drawing=off \
        label.drawing=off \
        width=900 \
        padding_left=0 \
        padding_right=0 \
        background.drawing=on \
        background.color=0x00000000 \
        background.height=30 \
        background.corner_radius=0 \
        background.image="$HOME/.config/sketchybar/images/mic_mute_led.png" \
        background.image.scale=1.0 \
        script="$PLUGIN_DIR/mic.sh" \
  --subscribe mic.core mic_change system_woke
